category and attribute tests
victorhausen/pytest-use-case pull request #1
Opened 2021-01-28 19:37 UTC by victorhausen

2021-01-28 19:50 UTC, lucastorresolist commented on requirements.txt
> +wrapt==1.12.1
Você utilizou o pytest?

2021-01-28 19:51 UTC, lucasdario requested changes

2021-01-28 19:51 UTC, lucasdario commented on src/models/category.py
> +    id_ = Column("ID", Integer, nullable=False, primary_key=True)
Maykon pediu uma base model também!

2021-01-28 19:51 UTC, lucasdario commented on src/tests/models/test_category.py
> +        too_large_name = "".join(["a" for e in range(100)])
`too_large_name = 'teste'*100` deve ter o mesmo efeito também!

2021-01-28 19:51 UTC, lucasdario commented on src/models/category.py
> +        if re.search(r"\d", name):
Porque não permitir números no nome? 
"Notebook 2 em 1"

2021-01-28 19:52 UTC, lucasdario commented on src/tests/models/test_category.py
> +        too_large_name = "".join(["a" for e in range(100)])
Apenas uma sugestão, talvez seja mais simples!

2021-01-28 20:51 UTC, victorhausen commented on requirements.txt
> +wrapt==1.12.1
atualizei o requirements.txt

2021-01-29 19:12 UTC, merged

2021-01-29 19:13 UTC, lucastorresolist approved these changes

2021-01-29 19:13 UTC, lucasdario approved these changes